### ISSUE TITLE
Problems using latest SD-FAT (beta)

### ISSUE THREAD

**Issue by homebrew-z80** [mecparts/TeensyBoardZ80#1]
It seems that sdfat-beta has progressed since the latest date of this teensyboardz80 source and it is unclear how to get a clean arduino build. Please clarify which build of sdfat  is required and whether the ".h" include should be for sdfat.h or sdfat-beta.h in teensyboardz80.ino

I am getting this build error :
In file included from C:\Users\rwdea\Downloads\TeensyBoardZ80-master\TeensyBoardZ80-master\TeensyBoardZ80\TeensyBoardZ80.ino:4:0:
C:\Users\rwdea\Documents\Arduino\libraries\SdFat-beta-2.1.4-beta.3\src/SdFat.h:452:2: warning: #warning File not defined because __has_include(FS.h) [-Wcpp]
 #warning File not defined because __has_include(FS.h)
  ^
In file included from C:\Users\rwdea\Downloads\TeensyBoardZ80-master\TeensyBoardZ80-master\TeensyBoardZ80\TeensyBoardZ80.ino:71:0:
abstraction_arduino.h: In function 'bool _RamLoad(char*, uint16)':
abstraction_arduino.h:15: error: 'File' was not declared in this scope
  File f;
  ^
abstraction_arduino.h:18: error: 'f' was not declared in this scope
  if (f = SD.open(filename, FILE_READ)) {

**Comment by mecparts** [comment]
As noted in the [References section at the at the readme](https://github.com/mecparts/TeensyBoardZ80#references), it's [my fork of SdFat-beta](https://github.com/mecparts/SdFat-beta) that's used.

**Comment by homebrew-z80** [comment]
Thanks,  I had missed that, and hoped it worked with more recent. I will
set that up and work with it.

Richard
